version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: my_nest_app_1
        volumes:
         - .:/app
        depends_on:
            - mydb
        environment: 
            NODE_ENV: development
            DATABASE_HOST: mydb
            DATABASE_PORT: 3306
            DATABASE_USER: root
            DATABASE_PASS: password
            DATABASE_NAME: nestapp
        ports:
            - "5000:5000"
        networks:
            - my-network
    mydb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mydb_1
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: nestapp
        networks:
          - my-network
networks:
  my-network: